# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def pods 
  pod 'Dip'
  pod 'SnapKit'
  pod 'Fabric', '1.8.2'
  pod 'Crashlytics', '3.11.1'
  pod 'IgyToast', '0.0.4'
  pod 'Networking', :path => '../Modules/Networking'
  pod 'Utils', :path => '../Modules/Utils'
end

target 'Rolique' do
end

target 'UI' do
  pods
end

